version: "3"

# A Flink cluster configuration in high-availability mode, with an ensemble of three 
# Zookeeper instances, two job managers (one active and one standby), two task managers 
# with four task slots or eight task slots total, and a cluster of three Kafka brokers 
# to consume messages from and produce messages to.
#
# The web dashboard is available on the host at http://localhost:8081/.
#
# The host's relative "shared" directory is mounted in the kafka containers to allow
# you to publish data to input topics.  
# 
# E.g. create an input in_topic topic:
#
#   docker-compose exec kafka-1 kafka-topics.sh \
#     --zookeeper zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181:/kafka \
#     --topic in_topic --create --partitions 10 --replication-factor 3
#
# create an output out_topic topic:
#
#   docker-compose exec kafka-1 kafka-topics.sh \
#     --zookeeper zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181:/kafka \
#     --topic out_topic --create --partitions 10 --replication-factor 3
#
# copy the the input data to the shared directory, then write it to the input topic:
#
#   docker-compose exec kafka-1 sh -c \
#     "kafka-console-producer.sh --broker-list kafka-1:9092 --topic in_topic < /shared/data > /dev/null"
#
#
# read the results from the output topic:
#
#   docker-compose exec kafka-1 kafka-console-consumer.sh --bootstrap-server kafka-1:9092 \
#     --topic out_topic --from-beginning 
#

services:

  zookeeper-1:
    image: elevy/zookeeper:v3.4.10
    environment:
      MYID: 1
      SERVERS: zookeeper-1,zookeeper-2,zookeeper-3
      SERVER_JVMFLAGS: -Xmx256M -Xms256M -server -XX:+UseG1GC

  zookeeper-2:
    image: elevy/zookeeper:v3.4.10
    environment:
      MYID: 2
      SERVERS: zookeeper-1,zookeeper-2,zookeeper-3
      SERVER_JVMFLAGS: -Xmx256M -Xms256M -server -XX:+UseG1GC

  zookeeper-3:
    image: elevy/zookeeper:v3.4.10
    environment:
      MYID: 3
      SERVERS: zookeeper-1,zookeeper-2,zookeeper-3
      SERVER_JVMFLAGS: -Xmx256M -Xms256M -server -XX:+UseG1GC

  kafka-1:
    image: elevy/kafka:v0.11.0.1
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      ADVERTISED_HOST_NAME: kafka-1
      ZOOKEEPER_SERVERS: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      ZOOKEEPER_ROOT: /kafka
      KAFKA_HEAP_OPTS: -Xmx256M -Xms256M
      #KAFKA_JVM_PERFORMANCE_OPTS: 
    volumes:
      - ./shared:/shared

  kafka-2:
    image: elevy/kafka:v0.11.0.1
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - "9092:9092"
    environment:
      ADVERTISED_HOST_NAME: kafka-2
      ZOOKEEPER_SERVERS: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      ZOOKEEPER_ROOT: /kafka
      KAFKA_HEAP_OPTS: -Xmx256M -Xms256M
      #KAFKA_JVM_PERFORMANCE_OPTS: 
    volumes:
      - ./shared:/shared

  kafka-3:
    image: elevy/kafka:v0.11.0.1
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      ADVERTISED_HOST_NAME: kafka-3
      ZOOKEEPER_SERVERS: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      ZOOKEEPER_ROOT: /kafka
      KAFKA_HEAP_OPTS: -Xmx256M -Xms256M
      #KAFKA_JVM_PERFORMANCE_OPTS: 
    volumes:
      - ./shared:/shared

  jobmanager-1:
    image: elevy/flink_jobmanager:v1.3.2
    hostname: jobmanager-1
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      # Web dashboard UI accessible from the host.
      - "127.0.0.1:8081:8081"
    environment:
      FLINK_ENV_JAVA_OPTS: -server -XX:+UseG1GC
      FLINK_JOBMANAGER_HEAP_MB: 256
      FLINK_HA: zookeeper
      FLINK_HA_CLUSTERID: cluster-1
      FLINK_HA_STORAGEDIR: file:///shared/ha
      FLINK_HA_ZOOKEEPER_QUORUM: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      FLINK_HA_ZOOKEEPER_PATH_ROOT: /flink/cluster-1
      FLINK_STATE_CHECKPOINTS_DIR: file:///shared/checkpoints/external
    volumes:
      - ./shared/flink:/shared

  jobmanager-2:
    image: elevy/flink_jobmanager:v1.3.2
    hostname: jobmanager-2
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      # Web dashboard UI accessible from the host.
      - "127.0.0.1:8082:8081"
    environment:
      FLINK_ENV_JAVA_OPTS: -server -XX:+UseG1GC
      FLINK_JOBMANAGER_HEAP_MB: 256
      FLINK_HA: zookeeper
      FLINK_HA_CLUSTERID: cluster-1
      FLINK_HA_STORAGEDIR: file:///shared/ha
      FLINK_HA_ZOOKEEPER_QUORUM: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      FLINK_HA_ZOOKEEPER_PATH_ROOT: /flink/cluster-1
      FLINK_STATE_CHECKPOINTS_DIR: file:///shared/checkpoints/external
    volumes:
      - ./shared/flink:/shared

  taskmanager-1:
    image: elevy/flink_taskmanager:v1.3.2
    hostname: taskmanager-1
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - jobmanager-1
      - jobmanager-2
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      FLINK_ENV_JAVA_OPTS: -server -XX:+UseG1GC
      FLINK_TASKMANAGER_HEAP_MB: 512
      FLINK_TASKMANAGER_NUMBEROFTASKSLOTS: 4
      FLINK_HA: zookeeper
      FLINK_HA_CLUSTERID: cluster-1
      FLINK_HA_STORAGEDIR: file:///shared/ha
      FLINK_HA_ZOOKEEPER_QUORUM: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      FLINK_HA_ZOOKEEPER_PATH_ROOT: /flink/cluster-1
      FLINK_STATE_CHECKPOINTS_DIR: file:///shared/checkpoints/external
    volumes:
      - ./shared/flink:/shared

  taskmanager-2:
    image: elevy/flink_taskmanager:v1.3.2
    hostname: taskmanager-2
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      - jobmanager-1
      - jobmanager-2
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      FLINK_ENV_JAVA_OPTS: -server -XX:+UseG1GC
      FLINK_TASKMANAGER_HEAP_MB: 512
      FLINK_TASKMANAGER_NUMBEROFTASKSLOTS: 4
      FLINK_HA: zookeeper
      FLINK_HA_CLUSTERID: cluster-1
      FLINK_HA_STORAGEDIR: file:///shared/ha
      FLINK_HA_ZOOKEEPER_QUORUM: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      FLINK_HA_ZOOKEEPER_PATH_ROOT: /flink/cluster-1
      FLINK_STATE_CHECKPOINTS_DIR: file:///shared/checkpoints/external
    volumes:
      - ./shared/flink:/shared


